/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  cacheDirectory: './node_modules/.cache/remix',
  future: {
    v2_dev: true,
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
  ignoredRouteFiles: ['**/.*', '**/*.test.{js,jsx,ts,tsx}'],
  postcss: true,
  serverModuleFormat: 'cjs',
  tailwind: true,
  serverDependenciesToBundle: [
    /^@react-pdf\/renderer.*/,
    /^@react-pdf.*/,
    'jay-peg',
    /^react-pdf.*/,
    /^yoga.*/,
    /^emoji.*/,
    '@arcgis/core',
    '@arcgis/core/layers/',
    'react-gauge-chart',
    'd3',
    /^d3-*/,
    'delaunator',
    'internmap',
    'robust-predicates',
    '@react-leaflet/core',
    'react-leaflet',
    'leaflet',
    /^@cloudinary\/url-gen/,
    /^@cloudinary\/transformation-builder-sdk/,
  ],
};