-- CreateTable
CREATE TABLE `InspectionsData` (
    `id` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `plotNumber` VARCHAR(191) NOT NULL,
    `plotExtent` DECIMAL(19, 2) NOT NULL,
    `propertyType` VARCHAR(191) NOT NULL,
    `location` VARCHAR(191) NOT NULL,
    `suburb` VARCHAR(191) NOT NULL,
    `price` DECIMAL(19, 2) NOT NULL,
    `transactionDate` DATETIME(3) NOT NULL,
    `titleDeed` VARCHAR(191) NOT NULL DEFAULT '',
    `status` VARCHAR(191) NOT NULL DEFAULT '',
    `plotDesc` VARCHAR(191) NOT NULL DEFAULT '',
    `numAirCons` INTEGER NOT NULL DEFAULT 0,
    `numParkingBays` INTEGER NOT NULL DEFAULT 0,
    `numOfStructures` INTEGER NOT NULL DEFAULT 0,
    `numToilets` INTEGER NOT NULL DEFAULT 0,
    `numStorerooms` INTEGER NOT NULL DEFAULT 0,
    `numBathrooms` INTEGER NOT NULL DEFAULT 0,
    `swimmingPool` VARCHAR(191) NOT NULL DEFAULT 'No',
    `paving` VARCHAR(191) NOT NULL DEFAULT 'None',
    `boundary` VARCHAR(191) NOT NULL DEFAULT 'None',
    `garageType` VARCHAR(191) NOT NULL DEFAULT 'None',
    `kitchen` VARCHAR(191) NOT NULL DEFAULT 'No',
    `wardrobe` VARCHAR(191) NOT NULL DEFAULT 'No',
    `roofModel` VARCHAR(191) NOT NULL DEFAULT 'None',
    `ceiling` VARCHAR(191) NOT NULL DEFAULT 'None',
    `interiorWallFinish` VARCHAR(191) NOT NULL DEFAULT 'Unknown',
    `longitude` DECIMAL(19, 15) NULL,
    `latitude` DECIMAL(19, 15) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
